trigger:
- master

pool:
  name: parisaagentpool
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: echo Build Started

# Install dependencies (if any) for your app here

- task: CopyFiles@2
  inputs:
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1'
    appType: 'webAppLinux'
    appName: 'mytestpipline'
    deployToSlotOrASE: true
    resourceGroupName: 'appserviceRg'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'